# LangChain Documentation RAG Configuration
models:
  provider: "openrouter"
  model: "mistralai/mistral-small-3.1-24b-instruct:free"
  temperature: 0.1
  max_tokens: 2000

embedding:
  provider: "local_sentencetransformers"
  model: "all-MiniLM-L6-v2"

vectordb:
  provider: "chroma"
  persist_directory: "./vectorstore/langchain_docs"
  collection_name: "langchain_documentation"
  anonymized_telemetry: false

chunking:
  strategy: "recursive"
  chunk_size: 1000
  overlap: 200

rag:
  top_k: 5
  search_type: "similarity"
  system_prompt: |
    You are a helpful assistant that answers questions about LangChain.
    Use the provided context to answer questions accurately and cite sources when possible.
    If you don't know something, say so rather than making up information.

agent:
  name: "LangChain Documentation Assistant"
  description: "RAG assistant for LangChain framework documentation"
  data_paths:
    - "./docs/langchain"