# Documentation RAG Configuration
models:
  provider: openrouter
  model: mistralai/mistral-small-3.1-24b-instruct:free
  model_kwargs:
    temperature: 0.8
    max_tokens: 2000

embedding:
  provider: local_sentencetransformers
  model: all-mpnet-base-v2
  device: cuda
  cache_folder: C:/Users/tyler/.cache/huggingface/sentence_transformers
  fallback_models:
    - all-MiniLM-L6-v2
    - all-mpnet-base-v2

vectordb:
  persist_directory: ./vectorstore/rag
  collection_name: rag_agent
  anonymized_telemetry: false

chunking:
  json_strategy: recursive
  text_strategy: recursive
  chunk_size: 500
  overlap: 120

rag:
  top_k: 4


system_prompt: |
  You are a helpful assistant that answers questions about supplied documentation.
  Use the provided context to answer questions accurately and cite sources when possible.
  If you don't know something, say so rather than making up information.

agent:
  name: rag_agent
  description: RAG assistant for ingested documentation
  agent_type: rag
  data_paths:
    - C:/Users/tyler/dev/_storage/.docs/openrouter_docs.txt
