models:
  provider: openrouter
  model: mistralai/mistral-small-3.1-24b-instruct:free
embedding:
  provider: huggingface_api
  model: BAAI/bge-base-en-v1.5
  device: cpu
vectordb:
  persist_directory: ./vector_storage
  collection_name: agentica_docs
system_prompt: |
  You are a helpful RAG developer assistant.
  Answer questions using the provided documentation.
data_paths:
  - docs
