models:
  provider: openrouter
  model: mistralai/mistral-small-3.1-24b-instruct:free
embedding:
  provider: local_sentencetransformers
  model: all-MiniLM-L6-v2
  device: cuda
vectordb:
  persist_directory: ./vector_storage
  collection_name: openrouter_docs
system_prompt: |
  You are a helpful RAG developer assistant.
  Answer questions using the provided documentation.
data_paths:
  - docs
