# Default RAG Agent Configuration
models:
  provider: "openrouter"
  model: "mistralai/mistral-small-24b-instruct-2501:free"
  model_kwargs:
    temperature: 0.7
    max_tokens: 500

embedding:
  provider: "local_sentencetransformers"
  model: "all-MiniLM-L6-v2"
  device: "cpu"
  cache_folder: null  # Will use HF_HOME if set
  fallback_models:
    - "all-MiniLM-L6-v2"
    - "all-mpnet-base-v2"

vectordb:
  persist_directory: "./vector_storage"
  collection_name: "default_docs"
  anonymized_telemetry: false
  settings:
    hnsw_space: "cosine"

chunking:
  json_strategy: "hierarchical"
  text_strategy: "semantic"
  chunk_size: 512
  overlap: 50

rag:
  top_k: 5
  similarity_threshold: 0.7
  enable_reranking: false

system_prompt: |
  You are a helpful RAG development assistant.
  You help users understand and work with retrieval-augmented generation systems.
  Always provide accurate and helpful information based on the retrieved context.

data_paths: []

# Environment variable names for API keys
openrouter_api_key_env: "OPENROUTER_API_KEY"

