models:
  language_model: "mistralai/mistral-small-3.1-24b-instruct:free"
  
# Embedding configuration - choose one
embedding:
  provider: "sentence_transformers"  # Options: "sentence_transformers", "huggingface"
  
  # SentenceTransformers local embedding (recommended for speed)
  sentence_transformers:
    model: "sentence-transformers/all-mpnet-base-v2"
    device: "cuda"  # or "cpu"
    local_files_only: true
    
  # HuggingFace API embedding (alternative)
  huggingface:
    model: "sentence-transformers/all-MiniLM-L6-v2"
    api_token_env: "HF_API_TOKEN"

vector_db:
  type: "chromadb"
  persist_directory: "./vector_storage"
  collection_name: "concordia_docs"

chunking:
  json_strategy: "hierarchical"
  text_strategy: "semantic"
  chunk_size: 512
  overlap: 50

rag:
  top_k: 5
  similarity_threshold: 0.7
  enable_reranking: false

# OpenRouter API configuration
openrouter:
  api_key_env: "OPENROUTER_API_KEY"
  base_url: "https://openrouter.ai/api/v1"
  model_kwargs:
    temperature: 0.7
    max_tokens: 512

# Data sources to ingest
data_sources:
  - path: "docs/references/openrouter_docs.txt"
    type: "text"
  - path: "concordia/.api_docs/_build/json/"
    type: "json_directory"
  - path: "docs/concordia_guides/"
    type: "text_directory"
