# Production RAG Configuration
models:
  provider: "openrouter"
  model: "openai/gpt-4-turbo"
  temperature: 0.2
  max_tokens: 3000
  model_kwargs:
    frequency_penalty: 0.1
    presence_penalty: 0.1

embedding:
  provider: "huggingface_api"
  model: "sentence-transformers/all-mpnet-base-v2"
  hf_api_token_env: "HF_API_TOKEN"
  fallback_models:
    - "sentence-transformers/all-MiniLM-L6-v2"
    - "intfloat/e5-base-v2"

vectordb:
  provider: "chroma"
  persist_directory: "./vectorstore/production"
  collection_name: "knowledge_base"
  anonymized_telemetry: false
  settings:
    hnsw_space: "cosine"

chunking:
  strategy: "semantic"
  chunk_size: 1200
  overlap: 300
  separators:
    - "\n\n"
    - "\n"
    - "\. "
    - " "

rag:
  top_k: 7
  search_type: "mmr"  # Maximum Marginal Relevance
  mmr_diversity_score: 0.3
  system_prompt: |
    You are an expert AI assistant with access to a comprehensive knowledge base.
    
    Instructions:
    1. Answer questions accurately using the provided context
    2. If multiple sources are relevant, synthesize information appropriately
    3. Always cite sources using [Source: filename] format
    4. If information is insufficient, acknowledge limitations
    5. Provide structured, well-formatted responses
    6. Include relevant examples when helpful
    
    Context: {context}
    
    Question: {question}
    
    Answer:

agent:
  name: "Production RAG Assistant"
  description: "High-performance RAG assistant for production use"
  data_paths:
    - "./data/documents"
    - "./data/manuals"
    - "./data/guides"
  openrouter_api_key_env: "OPENROUTER_API_KEY"
  hf_api_token_env: "HF_API_TOKEN"