agents:
  - name: Alice
    type: actor
    personality:
      curiosity: 0.9
      friendliness: 0.8
    memory:
      type: associative
      max_memories: 1000
      embedding:
        provider: local_sentencetransformers
        model: all-MiniLM-L6-v2
        device: cuda
    llm: openrouter

  - name: Bob
    type: actor
    personality:
      introversion: 0.6
      analytical: 0.9
    memory:
      type: associative
      max_memories: 1000
      embedding:
        provider: local_sentencetransformers
        model: all-MiniLM-L6-v2
        device: cpu
    llm: openrouter

  - name: Moderator
    type: archon
    authority_level: observer
    memory:
      type: basic
      max_memories: 1000
    llm: openrouter

engine:
  type: sequential
  steps: 5
  log_level: info
  response_word_limit: 60

scenario:
  description: "Alice and Bob suddenly find themselves in a simple room."
  initial_state:
    turn: 0
    conversation_log: []
    environment:
      locations:
        room:
          name: "Simple Room"
          description: "A simple room with white walls and basic furniture."
          objects:
            table:
              name: "Wooden Table"
              description: "A simple wooden table with four chairs."
              properties:
                searchable: true
                contents: ["notebook"]
                search_difficulty: "easy"
                search_message: "You search the table carefully, looking under papers and around the legs."
                empty_search_message: "You search the table but find nothing of interest."
            window:
              name: "Window"
              description: "A window looking out onto a peaceful garden."
              properties:
                openable: false
                examination_detail: "Through the window, you can see a peaceful garden with well-tended flower beds and a small fountain."
            chairs:
              name: "Four Chairs"
              description: "Four wooden chairs arranged around the table."
              properties:
                searchable: false
                moveable: false
                examination_detail: "The chairs are simple but well-made, with worn seats that suggest frequent use."
      items:
        notebook:
          name: "Notebook"
          description: "A small paper notebook with blank pages."
          properties:
            portable: true
            readable: true
            location: "hidden"
            content: "The first page of the notebook has the handwritten words `NOTHING IS REAL`, the rest of the notebook is empty."
  rules:
    - "Each agent must select ONE specific action from the available options."
    - "Actions must be concrete and environmental (examine, search, take, read, speak, wait)."
    - "The Archon narrates the environmental results of each action."
    - "Environmental changes persist and affect future interactions."
    - "Agents should explore the room and interact with objects to uncover mysteries."
    - "The notebook contains important information - finding and reading it may be significant."