# Chat Agent Configuration
models:
  provider: openrouter
  model: mistralai/mistral-small-3.1-24b-instruct:free
  model_kwargs:
    temperature: 0.8
    max_tokens: 2000





system_prompt: |
  You are a helpful and conversational AI assistant.
   Engage in a helpful, friendly, and informative back-and-forth chat with the user. 
   If you don't know something, say so rather than making up information.

agent:
  name: chat_agent
  description: Conversational chat assistant (no retrieval or document ingestion)
  agent_type: chat