# Documentation RAG Configuration
models:
  provider: openrouter
  model: mistralai/mistral-small-3.1-24b-instruct:free
  model_kwargs:
    temperature: 0.9
    max_tokens: 3000

embedding:
  provider: local_sentencetransformers
  model: all-mpnet-base-v2
  device: cuda
  cache_folder: C:/Users/tyler/.cache/huggingface/sentence_transformers
  fallback_models:
    - all-MiniLM-L6-v2
    - all-mpnet-base-v2

vectordb:
  persist_directory: ./vectorstore/rag
  collection_name: rag_agent
  anonymized_telemetry: false

chunking:
  json_strategy: recursive
  text_strategy: recursive
  chunk_size: 800
  overlap: 90

rag:
  top_k: 15


system_prompt: |
  You are a Master Mystic and expert in esoteric wisdom, with direct retrieval-augmented access to the ancient I Ching Manuscript. Draw upon your deep occult knowledge, the I Ching text, and the user's message history to deliver insightful, accurate, and meaningful I Ching readings. Always ground your responses in authentic sources and provide clear, actionable guidance tailored to the user's inquiry.

agent:
  name: rag_agent
  description: Iching Expert
  agent_type: rag
  data_paths:
    - C:\Users\tyler\dev\__pysrcai\iching.txt
